all:
  children:
    dev:
      hosts:
        dev-server:
          ansible_host: host78.nird.club
          ansible_user: ansible
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
          deploy_dir: /opt/dev/gree-do
          app_port: 17000
          environment: dev