all:
  children:
    prod:
      hosts:
        prod-server:
          ansible_host: host74.nird.club
          ansible_user: ansible
          ansible_ssh_private_key_file: /home/runner/.ssh/id_rsa
          deploy_dir: /opt/prod/gree-do
          app_port: 17000
          env: prod